version: "3.9"
services:
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
  web:
    image: 420810775770.dkr.ecr.us-east-1.amazonaws.com/snek
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
